# Generated by Django 3.1.6 on 2021-02-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
    ]
